### ISSUE TITLE
Vylepšit kartičky postav ("phone")

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/overly-fragile-relationships#35]
Tohle nemá moc vysokou prioritu.

- [ ] popisky typu `Dan: lover` by šlo nahradit větami typu "Currently dating Dan." nebo něco v tom smyslu. Pozor na to, že člověk může chodit s víc lidma (Dan).
- [ ] místo popisků vygenerovaných z tagů dát jednovětné popisky?

**Comment by petrroll** [comment]
Když někdo udělá všechny texty: jakej tag se má na co mapovat 1:1 tak easy to do.

**Comment by zouharvi** [comment]
Vyřešeno tím, že jsme tam dali bio.
