### ISSUE TITLE
Implementovat event: Eric vs. A+B

### ISSUE THREAD

**Issue by DrCuketa** [allemansratten/overly-fragile-relationships#45]
Ve chvíli co Alex a Beatrice spolu začnou chodit, tak se ukáže, že je Eric  religious a vadí mu LGBT+ relationship, nebude je mít rád. Pár tahů na to vidí, že to není issue, a ukáže se, že je closeted gay, a má crush na Cecila. Až ve chvíli co s ním začne chodit tak se usmíří s A a B.

- [ ] Ve chvíli co začnou A a B datovat, tak by je měl Eric dislikovat a zmensit se mu fondness
- [ ] Timed event - po ~dvou kolech, kdyz je venku s Cecilem, tak na sebe začnou mít crush, pokud maj dost vysokej fondness.
- [ ] když se daj dohromady, tak se Eric usmíří s Alex a Beatrice

**Comment by petrroll** [comment]
Rád udělám, ale někdo dodejte přesně texty.

**Comment by DrCuketa** [comment]
> 
> 
> Rád udělám, ale někdo dodejte přesně texty.

Eric said something about Alex's and Beatrice's relationship being unnatural and stormed off.
Eric and Cecil seem awfully close, for how harsh Eric was towards Alex and Beatrice...
Oh! Eric and Cecil started dating! Eric must have been repressing these feelings for a while. He went to apologise to Alex and Beatrice.

Něco takovýhohle? Ten první event by měl nastat až teprv když je s nima venku, ne jakmile spolu začnou chodit asi.
