### ISSUE TITLE
Upravit text pro události, které se dějou nepřítomným lidem

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/overly-fragile-relationships#46]
Některé věci se dějí i lidem, kteří s tebou zrovna nejsou - třeba Dan a Flavie se jednou za čas rozejdou a pak zase dají zpátky dohromady, nezávisle na tom, kam s nimi jdeš/nejdeš. Kdyby se nám podařilo tyhle věci odlišit textem od toho, co se děje lidem co jsou s tebou, tak by to bylo dobré.

Něco jako "meanwhile," nebo "Did you hear?"

Problém je, že se něco může stát třeba když jen část těch lidí (tzn nejčastěji asi jeden ze dvou) je přítomen, a pak nevím jak to vyřešit. Je potřeba nějak vymyslet.

**Comment by petrroll** [comment]
neřeší to přechod k mostly ručně napsaným description eventů?

**Comment by zouharvi** [comment]
Nemáme už automatické zprávy.
