### ISSUE TITLE
Barevný text

### ISSUE THREAD

**Issue by IAmWave** [allemansratten/overly-fragile-relationships#50]
Bylo by super color-codovat jména postav, o hodně líp by se to četlo v případě, že se stane víc věcí najednou.

https://www.html5gamedevs.com/topic/37309-rexbbcodetext-rextagtext/

Tady je na to nějaký plugin, ale vůbec nevím jak je použitelný. Možná to nepůjde.

**Comment by zouharvi** [comment]
Nedávám, sorry.
